% parameters of prior distribution
alpha = 3; % pseudocount of positive observations
beta  = 5; % pseudocount of negative observations

% observed data
x = 7; % number of positive observations
n = 8;  % total number of observations

% plot colors (from http://colorbrewer2.org/)
colors = [ 31, 120, 180; ...
           51, 160,  44; ...
          227,  26,  28] / 255;

% location of tikz output
figures_directory = 'figures';

theta = linspace(0, 1, 1000);

% see notes
prior      = @(theta) betapdf(theta, alpha, beta);
likelihood = @(theta) binopdf(x, n, theta);
posterior  = @(theta) betapdf(theta, alpha + x, beta + n - x);

clf;
hold('off');
prior_h = ...
    plot(theta, prior(theta), ...
         'color', colors(1, :));
hold('on');
likelihood_h = ...
    plot(theta, likelihood(theta), ...
         'color', colors(2, :));
posterior_h = ...
    plot(theta, posterior(theta), ...
         'color', colors(3, :));

legend([prior_h, likelihood_h, posterior_h], ...
       'prior', ...
       'likelihood', ...
       'posterior', ...
       'location', 'northwest');
legend('boxoff');

xlabel('$\theta$');

set(gca, 'box', 'off');

figure_name = 'beta_example';
matlab2tikz(sprintf('%s/%s.tex', figures_directory, figure_name), ...
              'height',           '\figureheight', ...
              'width',            '\figurewidth',  ...
              'parseStrings',     false,           ...
              'showInfo',         false,           ...
              'extraCode',        sprintf('\\tikzsetnextfilename{%s}', figure_name));